### ISSUE TITLE
Handle Composite Sites with Absolute Paths in their XML files

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-repository-p2#1]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

The following files:
* `compositeArtifacts.jar|xml`
* `compositeContent.jar|xml`

Can have absolute paths embedded in them, which would bypass Nexus Repository in the P2 client. Likely these should be rewritten to relative paths, and potentially turned into Proxy Repositories as well (since they will be external to the proxy you've created)

* **What feature or behavior is this required for?**

Fully supporting Composite Repositories

* **How could we solve this issue? (Not knowing is okay!)**

I think we would need to rewrite these xml files (the jar file is just a compressed xml file in reality), and potentially add a new step to P2 proxy creation that will take the absolute paths and use them to create new Proxy Repositories.

* **Anything else?**

Have fun :)

**Comment by laeubi** [comment]
newer versions of the P2 Repro format might use xz compressed files as well!

**Comment by laeubi** [comment]
Is this supposed to work with relative path also? Because for example http://download.eclipse.org/tools/orbit/downloads/drops/R20160520211859/repository when mirrored leads to an error because the compsite repros are locate to deep and the it fails to resolve.
I think, either relative or absolute, these files must be preprocessed and relocated into some kind of subdirectory for this to make it work.

**Comment by laeubi** [comment]
Another repro that does not work well... http://download.eclipse.org/jetty/updates/jetty-bundles-8.x
This has relative URLs, but they are not automatically mirrored.

**Comment by sewe** [comment]
I am facing the same issues as @laeubi, namely that it doesn't work for the Eclipse Orbit composite repos.

> I think, either relative or absolute, these files must be preprocessed and relocated into some kind of subdirectory for this to make it work.

:+1:

**Comment by proteus1121** [comment]
Fixed in 1.0.0 version of p2 (https://github.com/sonatype-nexus-community/nexus-repository-p2/pull/51)
