### ISSUE TITLE
Handle mirror.xml files

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-repository-p2#2]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

In some artifacts.xml files you'll see something similar to this:

```
<repository name='Eclipse Project Repository for Oxygen' type='org.eclipse.equinox.p2.artifact.repository.simpleRepository' version='1.0.0'>
  <properties size='4'>
    <property name='publishPackFilesAsSiblings' value='true'/>
    <property name='p2.compressed' value='true'/>
    <property name='p2.timestamp' value='1498225223662'/>
    <property name='p2.mirrorsURL' value='http://www.eclipse.org/downloads/download.php?format=xml&amp;file=/eclipse/updates/4.7/R-4.7-201706120950'/>
  </properties>
```

The p2.mirrorsURL gives a list of mirrors that are valid for downloading Eclipse packages.

What we want to do is write some code that if someone has configured Nexus Repository to proxy the actual downloads.eclipse.org URL (or really any URL that has a p2.mirrorsURL configured), to use the list of mirrors to do the actual downloads rather than the Eclipse foundation URL.

* **What feature or behavior is this required for?**

If people misconfigure Nexus Repository to use the downloads.eclipse.org, it can result in the UA being blacklisted, as I believe this has happened in the past.

* **How could we solve this issue? (Not knowing is okay!)**

You could take a look at how this was handled in Nexus Repository 2 for inspiration [here](https://github.com/sonatype/nexus-public/blob/nexus-2.x/plugins/p2/nexus-p2-repository-plugin/src/main/java/org/sonatype/nexus/plugins/p2/repository/proxy/P2ProxyRepositoryImpl.java#L159)

**Comment by proteus1121** [comment]
Hi, we are moving p2 source code to nexus public. This github page will be archived. Your issue https://issues.sonatype.org/browse/NEXUS-25238
