### ISSUE TITLE
P2 Group functionality

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-repository-p2#3]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Implement Group functionality! Allow people to group together a bunch of proxies so they can use one URL, which would simplify Eclipse setup for sure.

* **What feature or behavior is this required for?**

Group repositories.

* **How could we solve this issue? (Not knowing is okay!)**

A good first start would be to look at [how we did this in R](https://github.com/sonatype-nexus-community/nexus-repository-r) (since it's Nexus Repository 3 based), and then take a gander at [how we did it in Nexus Repository 2](https://github.com/sonatype/nexus-public/tree/nexus-2.x/plugins/p2/nexus-p2-repository-plugin/src/main/java/org/sonatype/nexus/plugins/p2/repository/group), as concepts etc... can be inspired from that. 

* **Anything else?**

I'll personally send anyone who does this all of my United Miles.

**Comment by mpiggott** [comment]
This one might be easy, the p2 group just needs to create and serve compositeContent.xml and compositeArtifacts.xml referencing the other groups.

**Comment by laeubi** [comment]
compositeContent.xml and compositeArtifacts.xml is IMO also the right way to do this since it would allow also caching if one of the combined ones are used seperately.

**Comment by simonmiller99** [comment]
@DarthHater Will they work for me in the UK ? Hmm.  Thanks for the links there, I was looking for past examples of how it was done. :)

**Comment by proteus1121** [comment]
Hi, we are moving p2 source code to nexus public. This github page will be archived. Your issue https://issues.sonatype.org/browse/NEXUS-25237
