### ISSUE TITLE
Support repository mappings

### ISSUE THREAD

**Issue by mpiggott** [sonatype-nexus-community/nexus-repository-p2#4]
p2 artifact repositories contain blocks which indicate how to construct URLs to request artifacts, e.g.
```
  <mappings size='5'>
    <rule filter='(&amp; (classifier=osgi.bundle) (format=packed))' output='${repoUrl}/plugins/${id}_${version}.jar.pack.gz'/>
    <rule filter='(&amp; (classifier=osgi.bundle))' output='${repoUrl}/plugins/${id}_${version}.jar'/>
    <rule filter='(&amp; (classifier=binary))' output='${repoUrl}/binary/${id}_${version}'/>
    <rule filter='(&amp; (classifier=org.eclipse.update.feature) (format=packed))' output='${repoUrl}/features/${id}_${version}.jar.pack.gz'/>
    <rule filter='(&amp; (classifier=org.eclipse.update.feature))' output='${repoUrl}/features/${id}_${version}.jar'/>
  </mappings>
```

These could map artifacts to arbitrary domains or relative paths outside of of the Nexus proxied repository

**Comment by mpiggott** [comment]
I imagine the plugin needs to replace the mappings section with its own version and store the original mapping in order to re-write requests to the correct path.

**Comment by laeubi** [comment]
Even though this is possible I have never seen an P2 repro actually using this, do you know of any repro that uses this technique?

**Comment by proteus1121** [comment]
Hi, we are moving p2 source code to nexus public. This github page will be archived. Your issue https://issues.sonatype.org/browse/NEXUS-25239
