### ISSUE TITLE
Documentation for using this plugin with Nexus 3

### ISSUE THREAD

**Issue by ShahimEssaid** [sonatype-nexus-community/nexus-repository-p2#56]
* **What are you trying to do?**

Learn about the P2 plugin for Nexus Repository Manager 3

The link under the "Using p2 With Nexus Repository Manager 3" heading in the README.md is broken. But when I go to the formats section of the Nexus 3 documentation I do find a "P2" format but it points back to this GitHub repository. Is there any documentation for installing and using this P2 plugin for Nexus 3 in addition to what's in the README.md in this repo?

**Comment by joedragons** [comment]
@ShahimEssaid That link used to point to https://github.com/sonatype-nexus-community/nexus-repository-p2/blob/63abf02724d84424fb893d49db78a66f95b25177/docs/P2_USER_DOCUMENTATION.md but we're revamping the plugin for release of 3.21.  At some point we need to update the docs so we can pull the project into main NXRM product (so you'll no longer need a plugin).  So the timing is just bad, once we release that doc will work.
I hope that helps you or soon (next week?) the link will just work.  I will leave this issue open til we release, but that's what's going on.

**Comment by joedragons** [comment]
I am closing this out since 3.21 came out yesterday.
