### ISSUE TITLE
Composite repo refs to composite: Issues on some P2 update sites (Orbit & Eclipse)

### ISSUE THREAD

**Issue by microwan** [sonatype-nexus-community/nexus-repository-p2#58]
Hello ,

I am using
Sonatype Nexus Repository Manager
OSS 3.20.1-01 and P2 plugin.

At the current , we are using CI Maven/Jenkins and Eclipse RCP.
All is working fine by using external P2 sites

Just some P2 sites with Nexus
Example 
i am trying to create a P2 repository (proxy) Version 0.0.3  for these 2 eclipse update site
http://download.eclipse.org/ecp/releases/releases_123/
https://download.eclipse.org/tools/orbit/downloads/drops/R20170307180635/
http://download.eclipse.org/tm/terminal/marketplace/

Is it solved in 1.0.0 version ?

         Best regards

                      Erwan

**Comment by proteus1121** [comment]
Hi, @microwan , issue which you described is related to composite repository topic. Actually I added in 1.0.0 support composite repositories, but only if it refs to simple repositories. So if composite repository refs to another composite repository - it's not supported. For example, if you add proxy to http://download.eclipse.org/ecp/releases/releases_123/ - it failed, but if you know which version you need exactly, for example RC1 and proxy https://download.eclipse.org/ecp/releases/releases_123/1230_RC1/ - it will be work fine. I did some investigation in this area in https://github.com/sonatype-nexus-community/nexus-repository-p2/pull/39/ , ping me here if you really need it, I will try to restore this one.

**Comment by mpiggott** [comment]
We included a fix for this in the 3.25 release of Nexus Repository Manager.
