### ISSUE TITLE
"(most) Permanent Install" doesn't work

### ISSUE THREAD

**Issue by zbsmax** [sonatype-nexus-community/nexus-repository-p2#6]
We are trying to do the "(most) Permanent Install" from the Readme.md to our Nexus 3.10.0-04.

We've copied the jar to the plugin-dir and inserted '<feature prerequisite="false" dependency="false">nexus-repository-p2</feature>' in '/opt/nexus-3.10.0-04/system/org/sonatype/nexus/assemblies/nexus-core-feature/3.10.0-04/nexus-core-feature-3.x.y-features.xml' (please look at attached nexus-core-feature-3.10.0-04-features.xml.txt).

The Server doesn't start (please look at attached nexus.log)

Do you have any hint?

[nexus-core-feature-3.10.0-04-features.xml.txt](https://github.com/sonatype-nexus-community/nexus-repository-p2/files/2013263/nexus-core-feature-3.10.0-04-features.xml.txt)
[nexus.log](https://github.com/sonatype-nexus-community/nexus-repository-p2/files/2013235/nexus.log)

**Comment by domeav** [comment]
Fresh nexus 3.12, "(most) permanent install" instructions worked out fine.

**Comment by pilot513** [comment]
I get error too: (nexus-3.13.0-01)

The plugin bandle builded locally by MAVEN 3.5.4
The plugin from "target" moved to dir:
/opt/nexus/system/org/sonatype/nexus/plugins/nexus-repository-p2
with perm. -rw-r--r--. 1 nexus nexus as "nexus-repository-p2-1.0.0-sources.jar"

The file /opt/nexus/system/org/sonatype/nexus/assemblies/nexus-core-feature/3.13.0-01/nexus-core-feature-3.13.0-01-features.xml   include lines:

` 
<feature version="1.0.0" prerequisite="false" dependency="false">nexus-repository-p2</feature> 
<feature name="nexus-repository-p2" description="org.sonatype.nexus.plugins:nexus-repository-p2" version="1.0.0">
        <details>org.sonatype.nexus.plugins:nexus-repository-p2</details>
        <bundle>mvn:org.sonatype.nexus.plugins/nexus-repository-p2/1.0.0</bundle>
</feature>`


When NEXUS 3.13.0-01 reloaded get error:

`*SYSTEM org.ops4j.pax.url.mvn.internal.AetherBasedResolver - Error resolving artifact org.sonatype.nexus.plugins:nexus-reposito
ry-p2:jar:1.0.0: [Could not find artifact org.sonatype.nexus.plugins:nexus-repository-p2:jar:1.0.0]
java.io.IOException: Error resolving artifact org.sonatype.nexus.plugins:nexus-repository-p2:jar:1.0.0: [Could not find artifact org.sonatype.nexus.plugins:nexus-repository-p2:jar:1.
0.0]`

**Comment by pilot513** [comment]
When try install/boot plugin from KARAF console:
`262 | Active    | 200 | 0                          | wrap_file__opt_nexus-3.13.0-01_system_com_sonatype_insight_scan_insight-scanner-model_2.8.1-01_insight-scanner-model-2.8.1-01.jar
263 | Active    | 200 | 0                          | wrap_file__opt_nexus-3.13.0-01_system_com_sonatype_licensing_license-bundle_1.4.3_license-bundle-1.4.3.jar
264 | Active    | 200 | 0                          | wrap_file__opt_nexus-3.13.0-01_system_org_apache_ant_ant-launcher_1.9.11_ant-launcher-1.9.11.jar
265 | Active    | 200 | 0                          | wrap_file__opt_nexus-3.13.0-01_system_org_apache_ant_ant_1.9.11_ant-1.9.11.jar
266 | Active    | 200 | 0                          | wrap_file__opt_nexus-3.13.0-01_system_org_redline-rpm_redline_1.2.5_redline-1.2.5.jar
267 | Active    | 200 | 0                          | wrap_file__opt_nexus-3.13.0-01_system_org_sonatype_sisu_sisu-odata4j_0.0.7_sisu-odata4j-0.0.7.jar
268 | Active    | 200 | 1.4.10                     | XStream Core
**269** | Installed | 200 |                            | file:///opt/nexus/system/org/sonatype/nexus/plugins/nexus-repository-p2/nexus-repository-p2-1.0.0-sources.jar
karaf@root()>
`

`karaf@root()> bundle:start <org.sonatype.nexus.plugins:nexus-repository-p2 ID>
2018-08-16 14:12:59,848+0300 ERROR [Karaf local console user karaf] *SYSTEM org.apache.karaf.shell.support.ShellUtil - Exception caught while executing command
java.lang.IllegalArgumentException: No matching bundles
        at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:59)
        at org.apache.karaf.bundle.command.BundlesCommand.execute(BundlesCommand.java:54)
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83)
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67)
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
        at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:274)
        at java.lang.Thread.run(Thread.java:748)
Error executing command: No matching bundles
karaf@root()>
`

**Comment by pilot513** [comment]
**Anybody will helped me ?**

**Comment by DarthHater** [comment]
I'll take a gander at this today!

**Comment by bdecker5** [comment]
Can you post the relative file path for the bundle? e.g. "NEXUS_DIR\system\org\sonatype\nexus\plugins\nexus-repository-p2\0.0.2"
I think you may be missing the version folder. e.g. "0.0.2"

**Comment by reuteran** [comment]
Any update on this? Im using version 1.03 and have the same problem (I created NEXUS_DIR\system\org\sonatype\nexus\plugins\nexus-repository-p2\1.0.3' and used '1.0.3' when editing the nexus core feature

**Comment by microwan** [comment]
Hello ,

Which version of Nexus Repository Manager ?
1.0.3 is only compliant for >3.21 
i have installed 0.0.3 and permanent install is working well

Sonatype Nexus Repository Manager
OSS 3.20.1-01

   Best regards

                   Erwan

**Comment by mpiggott** [comment]
Closing, we've included p2 as part of the distribution since 3.21
